version: '3'

services:
  redis:
    image: redis
    command: redis-server
    hostname: redis_server
    ports:
      - "6379:6379"
    networks:
      - network_tomcat


  nginx:
    container_name: load_balance_nginx
    hostname: load_balance_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default-jar.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network_tomcat
    depends_on:
      - redis
      - tomcat_1
      - tomcat_2

  tomcat_1:
    container_name: tomcat_1
    hostname: tomcat_1
    build:
      context: .
      dockerfile: Dockerfilejar
    volumes:
      - /etc/localtime:/etc/localtime:ro # para que o tomcat6_1 consiga acessar o timezone do servidor
    networks:
      - network_tomcat
#    ports:
#      - "8080:8080"
    depends_on:
      - redis

  tomcat_2:
    container_name: tomcat_2
    hostname: tomcat_2
    build:
      context: .
      dockerfile: Dockerfilejar
    volumes:
      - /etc/localtime:/etc/localtime:ro # para que o tomcat6_1 consiga acessar o timezone do servidor
    networks:
      - network_tomcat
#    ports:
#      - "8081:8080"
    depends_on:
      - redis


networks:
  network_tomcat:
    driver: bridge



